ondacast/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls")),
    path('', include('podcast.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user.views import *
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path ('login/',entrar, name="login"),
    path ('cadastro/', cadastrar,  name="cadastro"),
    path('logout/', sair, name="logout"),
    path('logout_criador', sair_criado, name="logout_criador"),
    path("excluir_conta", excluir_conta, name="excluir_conta"),
    path ('perfil', Perfil, name="perfil"),
    path ('configuracoes', Configuracoes, name="configuracoes"),
    path ('login_criador', login_criador, name="login_criador"),
    path ('cadastro_criador', cadastro_criador, name="cadastro_criador"),
]

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

user/views.py
import django

from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.db import IntegrityError 

from podcast.forms import PodcastForm
from podcast.models import Podcast, Episodio


def entrar(request):
    if request.method == "POST":
        nome_usuario = request.POST["username"]
        senha = request.POST["password"]
        usuario = authenticate(request, username=nome_usuario, password=senha)
        
        if usuario is not None:
            login(request, usuario)
            return redirect("index")
        else:
            messages.error(request, "nome de usuário ou senha incorretos.")
        
    return render(request, "user/login.html")

def cadastrar(request):
    if request.method == "POST":
        nome_usuario = request.POST["username"]
        email = request.POST["email"]
        senha = request.POST["password"]
        senha_confirmada = request.POST["password2"]

        if senha != senha_confirmada:
            messages.error(request, "As senhas não coincidem.")
            return redirect("cadastro")

        # Criar o novo usuário
        try:
            usuario = User.objects.create_user(username=nome_usuario, email=email, password=senha)
            usuario.groups.add(Group.objects.get(name="Usuário"))
            usuario.save()
            messages.success(request, "Usuário cadastrado com sucesso!")
            return redirect("login")  
        except:
            messages.error(request, "Erro ao criar usuário. Tente novamente.")
            return redirect("cadastro")
  
    return render(request, "user/cadastro.html")

def login_criador(request):
    if request.method == "POST":
        nome_podcast = request.POST["nome_podcast"]
        senha = request.POST["password"]
        usuario = authenticate(request, username=nome_podcast, password=senha)
        
        if usuario is not None:
            login(request, usuario)
            return redirect("index_criador")
        else:
            messages.error(request, "nome de usuário ou senha incorretos.")
        
    return render(request, "user/login_criador.html")
        

def cadastro_criador(request):
    print('cadastro_criador')  # Depuração

    if request.method == "POST":
        print('POST recebido')  # ✅ Adicionei um print para debug

        nome_podcast = request.POST["nome_podcast"]
        email = request.POST["email"]
        senha = request.POST["password1"]
        senha_confirmada = request.POST["password2"]

        if senha != senha_confirmada:
            messages.error(request, "As senhas não coincidem.")
            return redirect("cadastro_criador")

        try:
            usuario = User.objects.create_user(username=nome_podcast, email=email, password=senha)
            
            try:
                grupo = Group.objects.get(name="Criador") 
            except Group.DoesNotExist:  
                messages.error(request, "Erro: Grupo 'Criador' não existe. Contate um administrador.")
                return redirect("cadastro_criador")

            usuario.groups.add(grupo)
            messages.success(request, "Podcast cadastrado com sucesso!")
            return redirect("editar_perfil_criador")  
        
        except IntegrityError:
            messages.error(request, "Nome do podcast ou e-mail já está em uso. Escolha outro.")
            return redirect("cadastro_criador")

    return render(request, "user/cadastro_criador.html")


@login_required
def editar_podcast(request):
    try:
        podcast = Podcast.objects.get(criador=request.user)
        episodios = Episodio.objects.filter(podcast=podcast)
    except Podcast.DoesNotExist:
        podcast = None
        episodios = []

    if request.method == 'POST':
        form = PodcastForm(request.POST,request.FILES, instance=podcast)
        if form.is_valid():
            podcast=form.save(commit=False)
            podcast.criador = request.user
            podcast.save()
            return redirect('editar_perfil_criador')
    else:
        form = PodcastForm(instance=podcast)

    return render(request,'podcast/editar_perfil_criador.html', {
        'form':form,
        'podcast':podcast,
        'episodios':episodios})

@login_required
def excluir_conta(request):
    usuario = request.user  # Obtém o usuário autenticado
    
    
    # Impede a exclusão de superusuários
    if usuario.is_superuser:
        messages.error(request, "Superusuários não podem excluir suas contas.")
        return redirect("configuracoes")  

    if request.method == "POST":
        usuario.delete()  # Exclui o usuário do banco de dados
        logout(request)  
        messages.success(request, "Sua conta foi excluída com sucesso!")
        return redirect("login") 
    
    return redirect("configuracoes")  
def sair_criado(request):
    logout(request)
    return redirect("login_criador")
    
def sair(request):
    logout(request)
    return redirect("login")


def inicial_deslogado(request):
    return render(request, "user/inicial_deslogado.html")

def Perfil(request):
    return render(request, "user/perfil.html")

def Configuracoes(request):
    return render(request, "user/configuracoes.html")

user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "/user/css/styles.css" %}">
</head>
<body class="container-body">
    <header>
        <nav>
            {% block nav %}
            {% endblock %}
        </nav>
    </header>   

    <main>
        {% block main %}
        
        {% endblock %}
    </main>

    <footer>
        <div class="itens-rodape">
            <div class="links-rodape">
                <div class="links">
                    <h2>Links Úteis</h2>
                    <a href="">Politica de privacdade</a>
                    <a href="">Acessibilidade</a>
                    <a href="">Cookies</a>
                </div>
                <div class="empresa">
                    <h2>Empresa</h2>
                    <a href="">Sobre</a>
                    <a href="">Suporte</a>
                    <a href="">Aplicativo móvel</a>
                </div
            </div>
            <div class="icons-rodape">
                <a href=""><img src="{% static "/user/img/instagram.png" %}" alt=""></a>
                <a href=""><img src="{% static "/user/img/twitter.png" %}" alt=""></a>
                <a href=""><img src="{% static "/user/img/facebook.png" %}" alt=""></a>
                <p><span>&#169;</span> 2024 Ondacast</p>
            </div>
        </div>
    </footer>
    <script src="{% static "/user/js/scripts.js" %}"></script>    
</body>
</html>

user/templates/user/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="{% static "user/css/logins.css" %}">
    </head>
    <body>
        <div class="card-login">
            <div class="logo">
                <h1><u>Onda Cast</u></h1>
                <img src="{% static "user/img/headphones.png" %}" alt>
            </div>
            <h2><u>Cadastro</u></h2>
            <div class="form">
                {% if messages %}
                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}
                {% endif %}

                <form method="POST">
                    {% csrf_token %}
                    <label for="username">Usuário:</label>
                    <input type="text" name="username" required>

                    <label for="email">E-mail:</label>
                    <input type="email" name="email" required>

                    <label for="password">Senha:</label>
                    <input type="password" name="password" required>

                    <label for="password2">Confirme a Senha:</label>
                    <input type="password" name="password2" required>

                    <button type="submit">Cadastrar</button>
                </form>

                <div class="login-buttons">
                    <p>Já tem conta?&nbsp;<a href="{% url 'login' %}">Acessar
                            conta</a></p>
                </div>
            </body>
        </html>

user/templates/user/cadastro_criador.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "user/css/logins.css" %}">
</head>
<body>
    <div class="card-login">
        <div class="logo">
            <h1><u>Onda Cast</u></h1>
            <img src="{% static "user/img/headphones.png" %}" alt="">
        </div>
        <h2><u>Cadastro</u></h2>
        <class class="form">
            <form method="POST">
                {% csrf_token %}
            
                <label for="id_nome_podcast">Nome do Podcast:</label>
                <input type="text" name="nome_podcast" id="id_nome_podcast" required>
            
                <label for="id_email">E-mail:</label>
                <input type="email" name="email" id="id_email" required>
            
                <label for="id_password1">Senha:</label>
                <input type="password" name="password1" id="id_password1" required>
            
                <label for="id_password2">Confirme a Senha:</label>
                <input type="password" name="password2" id="id_password2" required>
            
                <button type="submit">Cadastrar</button>
            </form>
        </class>
        <class class="login-buttons">
            <p>Já tem conta de criador?<a href="{% url 'login_criador' %}">Acessar conta</a></p>
        </class>
</body>
</html>

user/templates/user/configuracoes.html
{% extends 'podcast/base.html' %}
{% load static %}

{% block navegar-home %}
<a href="{% url 'index' %}"><h1>OndaCast</h1></a>
<a href="{% url 'index' %}"></a><img src="{% static "user/img/headphones.png" %}" alt=""></a>
{% endblock %}

{% block nav %}
<div class="navbar">
    <div class="logo">
        <a href="{% url 'index' %}"><h1>OndaCast</h1></a>
        <a href="{% url 'index' %}"></a><img src="{% static "user/img/headphones.png" %}" alt=""></a>
    </div>
    <div class="nav-icons">
        <a href=""><?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
            <svg class="icone-svg-busca" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path opacity="0.1" d="M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" fill="#dcdcdc"/>
            <path d="M15 15L21 21" stroke="#dcdcdc" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="#dcdcdc" stroke-width="2"/>
            </svg></a>
       
        <button id="btnProfile"><svg class="icone-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
            <path opacity="1" d="M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12Z" fill="#dcdcdc"/>
            <path d="M16.807 19.0112C15.4398 19.9504 13.7841 20.5 12 20.5C10.2159 20.5 8.56023 19.9503 7.193 19.0111C6.58915 18.5963 6.33109 17.8062 6.68219 17.1632C7.41001 15.8302 8.90973 15 12 15C15.0903 15 16.59 15.8303 17.3178 17.1632C17.6689 17.8062 17.4108 18.5964 16.807 19.0112Z" fill="currentColor"/>
            <path d="M12 12C13.6569 12 15 10.6569 15 9C15 7.34315 13.6569 6 12 6C10.3432 6 9.00004 7.34315 9.00004 9C9.00004 10.6569 10.3432 12 12 12Z" fill="currentColor"/>
        </svg></button>
    </div>
    <div class="profileCard">
        <div class="link-profile-card">
            <ul>
                <li><a href="{% url 'perfil' %}">Conta</a></li>
            </ul>
            <ul>
                <li><a href="{% url 'configuracoes' %}">Configurações</a></li>
            </ul>
            <ul>
                <li><a href="">Favoritos</a></li>
            </ul>
            <div class="separa-barra"></div>
            <ul>
                <li><a href="{% url 'login' %}">Sair</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}
<div class="conteudo-main">
    <div class="card-lateral">
        <h2>Seus Interesses</h2>
        <button id="btnRecentes">Recentes</button>
        <button id="btnSeguindo">Seguindo</button>
        <div class="barra-branca"></div>
        <div class="containerRecentes">
            <div class="recentes">
                <a href="">
                    <img src="{% static "podcast/img/talentos_extraordinarios.png" %}" alt="">
                    <div class="info-card-recentes">
                        <h4>Talentos Extraordinários</h4>
                        <p>Aluísio Rego</p>
                    </div>
                </a>
            </div>
            <div class="recentes">
                <a href="">
                    <img src="{% static "podcast/img/mentes_inspiradoras.png" %}" alt="">
                    <div class="info-card-recentes">
                        <h4>Mentes Inspiradoras</h4>
                        <p>Com Aluísio Rego</p>
                    </div>
                </a>
            </div>
                        <div class="recentes">
                <a href="">
                    <img src="{% static "podcast/img/neabi.png" %}" alt="">
                    <div class="info-card-recentes">
                        <h4>NEABI</h4>
                        <p>Personalidades negras</p>
                    </div>
                </a>
            </div>
        </div>
        <div class="containerSeguindo" style="visibility: hidden;">
            <div class="seguindo">
                <a href="">
                    <img src="{% static "podcast/img/aluisio_seguindo.png" %}" alt="">
                    <div class="info-card-seguindo">
                        <h4>Aluísio Igor</h4>
                    </div>
                </a>
            </div>
            <div class="seguindo">
                <a href="">
                    <img src="{% static "podcast/img/momento_ifrn_seguindo.png" %}" alt="">
                    <div class="info-card-seguindo">
                        <h4>Momento IFRN</h4>
                    </div>
                </a>
            </div>
            <div class="seguindo">
                <a href="">
                    <img src="{% static "podcast/img/neabi_seguindo.png" %}" alt="">
                    <div class="info-card-seguindo">
                        <h4>NEABI</h4>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="card-principal">
        <h2>Configurações</h2>
        <div class="configs">
            <div class="textos-configuracoes">
                <h3>Autoplay</h3>
                <p>Ouça seus podcasts em sequência. Quando o episódio acabar colocaremos outro podcast para tocar.</p>
            </div>
            <div class="btn-check">
                <input type="checkbox" id="check">
                <label for="check" class="switch">  
                    <span class="slider"></span>
                </label>
            </div>
        </div>
        
        <div class="configs">
            <div class="textos-configuracoes">
                <h3>Downloads</h3>
                <p>Conteúdo baixado para ouvir offline. Localização do armazenamento offline:</p>
                <input type="text" value="C:\Users\aluisioigor\AppData\Packages\OndaCast\OndaCast_offline" id="" readonly>
            </div>

            <div class="btn-downloads">
                <button>Mudar local de Downloads</button>
                <button>Remover todos os Downloads</button>
            </div>
        </div>

        <div class="configs configs-btns">
            <div class="btn-criar-conta-criador">
                <a href="{% url 'login_criador' %}"><button>Criar conta de CRIADOR</button></a>
            </div>
            <div class="btn-excluir-conta">
                <button>Excluir Conta</button>
            </div>  
        </div>

        <div class="card-excluir-conta">
            <h3>Deseja realmente excluir a sua conta?</h3>
            <ul>
                <li>Não receberá mais notificações dos seus podcasts favoritos</li>
                <li>Perderá seus podcasts baixados e salvos</li>
                <li>O seu histórico de podcasts será perdido</li>
            </ul>
            <div>
            <form action="{% url 'excluir_conta' %}" method="POST">
                {% csrf_token %}
                <button id="excluir-conta" type="submit">Sim, excluir minha conta</button>
            </form>
            
            <button id="manter-conta" href="{% url 'perfil' %}">Cancelar</button>
            </div>
        </div>
    </div>  
</div>
{% endblock %}

{% block javascript %}
    <script src="{% static "user/js/config.js" %}"></script>
{% endblock %}

user/templates/user/index.html
{% extends 'user/base.html' %}
{% load static %}

{% block nav %}
<div class="navbar">
    <div class="logo">
        <h1>OndaCast</h1>
        <img src="{% static "/user/img/headphones.png" %}" alt="">
    </div>
    <div class="nav-icons">
        <a href=""><?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
            <svg class="icone-svg-busca" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path opacity="0.1" d="M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" fill="#dcdcdc"/>
            <path d="M15 15L21 21" stroke="#dcdcdc" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="#dcdcdc" stroke-width="2"/>
            </svg></a>
        <a href=""><?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
            <svg class="icone-svg" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><title>ionicons-v5-f</title>
                <path d="M448,256c0-106-86-192-192-192S64,150,64,256s86,192,192,192S448,362,448,256Z" style="fill:#dcdcdc;stroke:#dcdcdc;stroke-miterlimit:10;stroke-width:32px"/>
                <path d="M256,360a16,16,0,0,1-9-2.78c-39.3-26.68-56.32-45-65.7-56.41-20-24.37-29.58-49.4-29.3-76.5.31-31.06,25.22-56.33,55.53-56.33,20.4,0,35,10.63,44.1,20.41a6,6,0,0,0,8.72,0c9.11-9.78,23.7-20.41,44.1-20.41,30.31,0,55.22,25.27,55.53,56.33.28,27.1-9.31,52.13-29.3,76.5-9.38,11.44-26.4,29.73-65.7,56.41A16,16,0,0,1,256,360Z" fill="currentColor"/>
            </svg></a>
        <a href=""><?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
            <svg class="icone-svg" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><title>ionicons-v5-j</title>
                <path d="M448,256c0-106-86-192-192-192S64,150,64,256s86,192,192,192S448,362,448,256Z" style="fill:#dcdcdc;stroke:#dcdcdc;stroke-miterlimit:10;stroke-width:32px"/>
                <path d="M365.2,313c-16.33-19.34-27.86-27.47-27.86-80.8,0-48.86-25.78-66.23-47-74.67a11.39,11.39,0,0,1-6.34-6.68C280.29,138.6,269.88,128,256,128s-24.31,10.6-28,22.86a11.35,11.35,0,0,1-6.33,6.68c-21.24,8.46-47,25.8-47,74.67,0,53.33-11.54,61.46-27.87,80.8-6.77,8-.65,23,11.19,23H354C365.77,336,371.94,321,365.2,313Z" fill="currentColor"/>
                <path d="M220.24,352a4,4,0,0,0-4,4.42C218.49,375.14,235.11,384,256,384c20.67,0,37.14-9.15,39.66-27.52a4,4,0,0,0-4-4.48Z" fill="currentColor"/></svg></a>
        <button id="btnProfile"><svg class="icone-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
            <path opacity="1" d="M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12Z" fill="#dcdcdc"/>
            <path d="M16.807 19.0112C15.4398 19.9504 13.7841 20.5 12 20.5C10.2159 20.5 8.56023 19.9503 7.193 19.0111C6.58915 18.5963 6.33109 17.8062 6.68219 17.1632C7.41001 15.8302 8.90973 15 12 15C15.0903 15 16.59 15.8303 17.3178 17.1632C17.6689 17.8062 17.4108 18.5964 16.807 19.0112Z" fill="currentColor"/>
            <path d="M12 12C13.6569 12 15 10.6569 15 9C15 7.34315 13.6569 6 12 6C10.3432 6 9.00004 7.34315 9.00004 9C9.00004 10.6569 10.3432 12 12 12Z" fill="currentColor"/>
        </svg></button>
    </div>
    <div class="profileCard">
        <div class="link-profile-card">
            <ul>
                <li><a href="">Conta</a></li>
            </ul>
            <ul>
                <li><a href="">Configurações</a></li>
            </ul>
            <ul>
                <li><a href="">Downloads</a></li>
            </ul>
            <div class="separa-barra"></div>
            <ul>
                <li><a href="">Sair</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}
<div class="conteudo-main">
    <div class="card-lateral">
        <h2>Seus Interesses</h2>
        <button id="btnRecentes">Recentes</button>
        <button id="btnSeguindo">Seguindo</button>
        <div class="barra-branca"></div>
        <div class="containerRecentes">
            <div class="recentes">
                <a href="">
                    <img src="{% static "/user/img/talentos_extraordinarios.png" %}" alt="">
                    <div class="info-card-recentes">
                        <h4>Talentos Extraordinários</h4>
                        <p>Aluísio Rego</p>
                    </div>
                </a>
            </div>
            <div class="recentes">
                <a href="">
                    <img src="{% static "/user/img/mentes_inspiradoras.png" %}" alt="">
                    <div class="info-card-recentes">
                        <h4>Mentes Inspiradoras</h4>
                        <p>Com Aluísio Rego</p>
                    </div>
                </a>
            </div>
                        <div class="recentes">
                <a href="">
                    <img src="{% static "/user/img/neabi.png" %}" alt="">
                    <div class="info-card-recentes">
                        <h4>NEABI</h4>
                        <p>Personalidades negras</p>
                    </div>
                </a>
            </div>
        </div>
        <div class="containerSeguindo" style="visibility: hidden;">
            <div class="seguindo">
                <a href="">
                    <img src="{% static "/user/img/aluisio_seguindo.png" %}" alt="">
                    <div class="info-card-seguindo">
                        <h4>Aluísio Igor</h4>
                    </div>
                </a>
            </div>
            <div class="seguindo">
                <a href="">
                    <img src="{% static "/user/img/momento_ifrn_seguindo.png" %}" alt="">
                    <div class="info-card-seguindo">
                        <h4>Momento IFRN</h4>
                    </div>
                </a>
            </div>
            <div class="seguindo">
                <a href="">
                    <img src="{% static "/user/img/neabi_seguindo.png" %}" alt="">
                    <div class="info-card-seguindo">
                        <h4>NEABI</h4>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="card-principal">
        <h2>Principais Temas</h2>
    </div>
</div>
{% endblock %}

user/templates/user/inicial_deslogado.html
{% extends 'user/base.html' %}
{% load static %}

{% block nav %}
<link rel="stylesheet" href="{% static "/user/css/inicial_deslogado.css" %}">
<div class="navbar">
    <div class="logo">
        <h1>OndaCast</h1>
        <img src="{% static "/user/img/headphones.png" %}" alt="">
    </div>
    <div class="nav-icons">
        
    </div>
    <div class="profileCard">
        <div class="link-profile-card">
            <ul>
                <li><a href="">Conta</a></li>
            </ul>
            <ul>
                <li><a href="">Configurações</a></li>
            </ul>
            <ul>
                <li><a href="">Downloads</a></li>
            </ul>
            <div class="separa-barra"></div>
            <ul>
                <li><a href="">Sair</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}
<div class="conteudo-main">
    <div class="card-lateral">
        <h2>Seus Interesses</h2>
        <button id="btnRecentes">Recentes</button>
        <button id="btnSeguindo">Seguindo</button>
        <div class="barra-branca"></div>
        <div class="containerRecentes">
            <div class="recentes">
               <div class="divAviso">
                <h1 class="h1"> Conecte-se para personalizar</h1>
               </div>
            </div>  
        </div>
        <div class="containerSeguindo" style="visibility: hidden;">
           
        </div>
    </div>
    <div class="card-principal">
        <h2>Principais Temas</h2>
    </div>
</div>
{% endblock %}

user/templates/user/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="{% static "user/css/logins.css" %}">
    </head>
    <body>
        <div class="card-login">
            <div class="logo">
                <h1><u>Onda Cast</u></h1>
                <img src="{% static "user/img/headphones.png" %}" alt>
            </div>
            <h2>login</h2>
            <div class="form">
                {% if messages %}
                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}
                {% endif %}

                <form method="POST">
                    {% csrf_token %}
                    <label for="username">Usuário:</label>
                    <input type="text" name="username" required>

                    <label for="password">Senha:</label>
                    <input type="password" name="password" required>

                    <button type="submit">Entrar</button>
                </form>

                <class class="login-buttons">

                    <a href="#">Esqueceu sua senha?</a>
                    <a href="{% url 'login_criador' %}">Acessar conta de
                        desenvolvedor</a>
                    <p style="margin-top: 40px;">Não tem conta?&nbsp;<a
                            href="{% url 'cadastro' %}">Cadastrar</a></p>
                </class>

            </div>
        </body>
    </html>

user/templates/user/login_criador.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "user/css/logins.css" %}">
</head>
<body>
    <div class="card-login">
        <div class="logo">
            <h1><u>Onda Cast</u></h1>
            <img src="{% static "user/img/headphones.png" %}" alt="">
        </div>
        <h2><u>login</u></h2>
        <class class="form">
            <form method="POST">
                {% csrf_token %}
            
                <label for="id_nome_podcast">Nome do Podcast:</label>
                <input type="text" name="nome_podcast" id="id_nome_podcast" required>
            
                <label for="id_password">Senha:</label>
                <input type="password" name="password" id="id_password" required>
            
                <button type="submit">Entrar</button>
            </form>
        </class>
        <class class="login-buttons">
            <a href="#">Esqueceu sua senha?</a>
            <a href="{% url 'login' %}">Acessar conta de ouvinte</a>
            <p style="margin-top: 40px;">Não tem uma conta?<a href="{% url 'cadastro_criador' %}">Criar conta</a></p>
        </class>
    </div>
</body>
</html>